### ISSUE TITLE
Module build failed: Error: ENOENT: no such file or directory /angular-morris-js/src/index.ts

### ISSUE THREAD

**Issue by pierresh** [mika-el/angular-morris-js#1]
Hello,

I am trying to implement this wrapper within an Ionic 3 mobile app (with Angular 5.0.0), but I get the following error message:

> Module build failed: Error: ENOENT: no such file or directory, open '/Applications/XAMPP/xamppfiles/htdocs/my_app/node_modules/angular-morris-js/src/index.ts'

I found an index.js file in angular-morris-js/src but not index.ts. If I rename it as index.ts then it requires angular-morris-js/src/index.js.map:
> Module build failed: Error: ENOENT: no such file or directory, open '/Applications/XAMPP/xamppfiles/htdocs/my_app/node_modules/angular-morris-js/src/index.js.map

Below is my configuration related to angular-morris-js:

In **app.module.ts**:
```
import { MorrisJsModule } from 'angular-morris-js/src';

@NgModule({
  imports: [..., MorrisJsModule, ...]
})
```

In **my_page.ts**:
```
import { MorrisJsModule } from 'angular-morris-js/src';

	ngOnInit() {
		this.chartLineData = [
			{ y: '2005', a: 75,  b: 65 },
			{ y: '2008', a: 50,  b: 40 },
			{ y: '2009', a: 75,  b: 65 },
			{ y: '2010', a: 50,  b: 40 },
			{ y: '2011', a: 75,  b: 65 },
			{ y: '2012', a: 100, b: 90 }
		];
		this.chartLineOptions = {
			xkey: 'y',
			ykeys: ['a', 'b'],
			labels: ['Series A', 'Series B'],
			resize: true
		};
	}
```

In **my_page.html**:
```
		<div mk-morris-js 	[options]="chartLineOptions" 
						[data]="chartLineData" 
						type="Line" 
						style="height: 500px; width: 100%;"></div>
```

Do you have any idea what may be wrong in my configuration? Thanks!

PS: I created a fork of Morris (https://pierresh.github.io/morris.js/) that includes many new features and I removed the need for jQuery, that may be better as dependency for this project ;-)

**Comment by mika-el** [comment]
Hi,

You need to remove src for the import.

`import { MorrisJsModule } from 'angular-morris-js';`

Great for the fork without jQuery, i'll check that :-)

**Comment by pierresh** [comment]
Hello, thanks a lot for your quick feedback. Nevertheless, I added /src because I got an error without it as shown below:

![image](https://user-images.githubusercontent.com/7520095/35503896-6dc36072-051c-11e8-8c43-5fe5f5e2d3f0.png)

My folder is like this:
![image](https://user-images.githubusercontent.com/7520095/35503957-9a77fc18-051c-11e8-813a-a35a7bfd7696.png)

**Comment by mika-el** [comment]
You're welcome :-)
This folder is the git repo, you need to use the builded npm package `npm install angular-morris-js --save`

**Comment by pierresh** [comment]
Ahh yes, you are right, it works perfectly, thanks a lot !
